---
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Nassau
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code.thebritishaccent.net #optional
    volumes:
      - ./config:/config
      - ./data:/data
      - ../dashmachine0.7:/data/dashmachine
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.${REVERSE_HOST}`)"
      - "traefik.http.routers.code-server.entrypoints=web-secure"
      - "traefik.http.routers.code-server.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse