version: '3.3'
services:
  pms-docker:
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Vancouver
      - PLEX_CLAIM
      - VERSION=docker
      - 'ADVERTISE_IP=http://10.8.0.160:32400/'
    volumes:
        - '../../volumes/plex-stack/config-plex/config:/config'
        - '../../volumes/plex-stack/config-plex/transcode:/transcode'
        
        - '/mnt/media/audio:/data-audio'
        - '/mnt/media/photo:/data-photo'
        - '/mnt/media/video:/data'     
    image: plexinc/pms-docker
    #hostname: plex.${REVERSE_HOST}
    # labels: 
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.plex.rule=Host(`plex.${REVERSE_HOST}`)"
    #   - "traefik.http.routers.plex.entrypoints=web-secure"
    #   - "traefik.http.routers.plex.tls=true"
    #   - "traefik.http.services.plex.loadbalancer.server.port=32400"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse
