version: '3.3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx
      - ./keys:/etc/ssl/private
      - ./certs:/etc/ssl/certs
