---
version: "3.4"
services:
  pyload:
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Nassau
    volumes:
      - ../../volumes/pyload/config:/config
      - ../../volumes/pyload/downloads:/downloads
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.pyload.rule=Host(`pyload.${REVERSE_HOST}`)"
      - "traefik.http.routers.pyload.entrypoints=web-secure"
      - "traefik.http.routers.pyload.tls=true"
      - "traefik.http.services.pyload.loadbalancer.server.port=8000"
    networks: 
      - reverse
    healthcheck:
      test: curl --fail http://localhost:8000/json/status || exit 1
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  reverse:
    external:
      name: reverse