---
version: "2"
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1001
    volumes:
      - ./config:/config
      - /mnt/virt/manga:/books
      - /etc/timezone:/etc/timezone
    user: "1000:1000"
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`komga.${REVERSE_HOST}`)"
      - "traefik.http.routers.komga.entrypoints=web-secure"
      - "traefik.http.routers.komga.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse