version: '3.4'
services:
  stash-sfw:
    image: stashapp/stash:latest
    container_name: stash-sfw
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro

      ## Keep configs here.
      - NULL/config:/root/.stash

      ## Point this at your collection.
      - /mnt/virt/gdrive/crypt/Anime:/data/Anime
      - /mnt/virt/gdrive/crypt/Memes:/data/Memes

      ## This is where your stash's metadata lives
      - NULL/metadata:/metadata

      ## Any other cache content.
      - NULL/cache:/cache
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - NULL/generated:/generated
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.stash-sfw.rule=Host(`memes.${REVERSE_HOST}`)"
      - "traefik.http.routers.stash-sfw.entrypoints=web-secure"
      - "traefik.http.routers.stash-sfw.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse