version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
      - "./home:/storage:ro"
      - "./watch:/watch:rw"
      - "./output:/output:rw"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake.rule=Host(`handbrake.${REVERSE_HOST}`)"
      - "traefik.http.routers.handbrake.entrypoints=web-secure"
      - "traefik.http.routers.handbrake.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse