version: "3.3"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: 'always'
    security_opt:
      - no-new-privileges:true
    secrets:
      - CF_DNS_API_TOKEN
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/CF_DNS_API_TOKEN
    command:
      # Globals
      - "--log.level=DEBUG"
      - "--api=true"
      - "--pilot.token=${PILOT_TOKEN}"
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # Providers
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      # ACME
      - '--certificatesresolvers.cloudflare.acme.email=${EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      - '--certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53'
      - '--certificatesresolvers.cloudflare.acme.storage=/acme.json'
      #- '--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=45'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - './acme.json:/acme.json'
     # - "./config/:/configuration/"
    labels: 
      - "traefik.enable=true"
      
      # global wildcard certificates
      - 'traefik.http.routers.wildcard-certs.tls.certresolver=cloudflare'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].main=*.${DOMAIN}'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].sans=${DOMAIN}'

      # dashboard
      - "traefik.http.routers.api.rule=Host(`traefik.${REVERSE_HOST}`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.entrypoints=web-secure"
      - 'traefik.http.routers.api.service=api@internal'
      
    networks:
      - reverse

  ###
  ### Authelia Containers
  ###
  authelia:
    image: authelia/authelia
    container_name: authelia
    depends_on: 
      - redis
    volumes:
      - ../../volumes/traefik/authelia:/config
    networks:
      - reverse
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.${REVERSE_HOST}`)'
      - 'traefik.http.routers.authelia.entrypoints=web-secure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${REVERSE_HOST}/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ../../volumes/traefik/redis:/data
    networks:
      - reverse
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`secure.${REVERSE_HOST}`)'
      - 'traefik.http.routers.whoami.entrypoints=web-secure'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.routers.whoami.middlewares=authelia@docker'
    networks:
      - reverse

networks:
  reverse:
    external:
      name: reverse

secrets:
  CF_DNS_API_TOKEN:
    file: ./CF_DNS_API_TOKEN.secret
