[file]

[http.services]
  # Raspi 4
  [http.services.hassio.loadBalancer]
    [[http.services.hassio.loadBalancer.servers]]
      url = "http://10.8.0.109:8123"

  [http.services.gitea.loadBalancer]
    [[http.services.gitea.loadBalancer.servers]]
      url = "http://10.8.0.109:3000"

  [http.services.snapdrop.loadBalancer]
    [[http.services.snapdrop.loadBalancer.servers]]
      url = "http://10.8.0.109:8080"

  [http.services.pihole0.loadBalancer]
    [[http.services.pihole0.loadBalancer.servers]]
      url = "http://10.8.0.109:8182"
  
  [http.services.bookstack.loadBalancer]
    [[http.services.bookstack.loadBalancer.servers]]
      url = "http://10.8.0.109:6875"
  
  # Raspi 3
  [http.services.pihole1.loadBalancer]
    [[http.services.pihole1.loadBalancer.servers]]
      url = "http://10.8.0.161:8182"

[http.routers]
  # Raspi 4
  [http.routers.hassio]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`home.thebritishaccent.net`)"
    service = "hassio"
	[http.routers.hassio.tls]
  
  [http.routers.gitea]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`gitea.thebritishaccent.net`)"
    service = "gitea"
	[http.routers.gitea.tls]

  [http.routers.snapdrop]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`drop.thebritishaccent.net`)"
    service = "snapdrop"
	[http.routers.snapdrop.tls]
  
  [http.routers.pihole0]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`pihole0.thebritishaccent.net`)"
    service = "pihole0"
	[http.routers.pihole0.tls]

  [http.routers.bookstack]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`bookstack.thebritishaccent.net`)"
    service = "bookstack"
	[http.routers.bookstack.tls]

  # Raspi 3
  [http.routers.pihole1]
    # won't listen to entry point web
    entryPoints = ["web-secure"]
    rule = "Host(`pihole1.thebritishaccent.net`)"
    service = "pihole1"
	[http.routers.pihole1.tls]