---
version: "3.4"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - '../../volumes/calibre-web/config:/config'
      - '/mnt/virt/gdrive/crypt/Books:/books'
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre.${REVERSE_HOST}`)"
      - "traefik.http.routers.calibre.entrypoints=web-secure"
      - "traefik.http.routers.calibre.tls=true"
    networks: 
      - reverse
    healthcheck:
      test: curl --fail http://localhost:8083 || exit 1
      interval: 15s
      retries: 5
      start_period: 120s
      timeout: 10s

networks:
  reverse:
    external:
      name: reverse