[MyIpData]
platform = 'curl'
resource = 'https://api.myip.com'
value_template = '<div class="row center-align"><div class="col s12"><h5><i class="material-icons-outlined" style="position:relative; top: 4px;">dns</i> My IP Address</h5><span class="theme-primary-text">{{value.ip}}</span></div></div>'
response_type = 'json'

[pihole-data]
platform = 'pihole'
host = '10.8.0.161'
password = 'cQpSMU7J'
value_template = '<br><div class="row center-align"><div class="col s12"><h5><i class="material-icons-outlined" style="position:relative; top: 4px;">dns</i> Pihole</h5>Ads Blocked Today: {{ blocked }}<br>Status: {{ status }}<br>Queries today: {{ queries }}</div></div>'