version: '3.3'
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn:v4_2_x
    container_name: qbittorrent
    restart: unless-stopped
    privileged: true
    environment:
        - VPN_ENABLED=yes
        - VPN_USERNAME
        - VPN_PASSWORD
        - LAN_NETWORK=10.8.0.0/24
        - 'NAME_SERVERS=8.8.8.8'
    volumes:
        - '../../volumes/ingress-stack/config-qbittorrent:/config'
        - '/mnt/virt:/data'
    labels: 
      - "traefik.enable=true"

      - "traefik.http.routers.qbittorrent.rule=Host(`qbt.${REVERSE_HOST}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web-secure"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

      - "traefik.http.routers.soulseek.rule=Host(`soul.${REVERSE_HOST}`)"
      - "traefik.http.routers.soulseek.entrypoints=web-secure"
      - "traefik.http.routers.soulseek.tls=true"
      - "traefik.http.routers.soulseek.service=soulseek"
      - "traefik.http.services.soulseek.loadbalancer.server.port=6080"
    networks: 
      - reverse

  soulseek:
    image: realies/soulseek
    container_name: soulseek
    restart: unless-stopped
    depends_on:
      - qbittorrentvpn
    environment:
      - pgid=1000
      - puid=1000
      - resize=scale
      - resolution=1280x720
    volumes:
        - '../../volumes/ingress-stack/soulseek/appdata:/data/.SoulseekQt'
        - '../../volumes/ingress-stack/soulseek/downloads:/data/Soulseek Downloads'
        - '/mnt/virt/Music:/Music'
        - '../../volumes/ingress-stack/soulseek/logs:/data/Soulseek Chat Logs'
    network_mode: "service:qbittorrentvpn"
    stdin_open: true
    tty: true
    # Curl is not installed in container by default
    # healthcheck:
    #   test: [ $(curl -s "http://ip-api.com/line?fields=countryCode") = "CH" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - '../../volumes/ingress-stack/config-sonarr:/config'
      - '/mnt/virt/:/data'
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${REVERSE_HOST}`)"
      - "traefik.http.routers.sonarr.entrypoints=web-secure"
      - "traefik.http.routers.sonarr.tls=true"
    networks: 
      - reverse
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - '../../volumes/ingress-stack/config-radarr:/config'
      - '/mnt/virt/:/data'
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${REVERSE_HOST}`)"
      - "traefik.http.routers.radarr.entrypoints=web-secure"
      - "traefik.http.routers.radarr.tls=true"
    networks: 
      - reverse
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - '../../volumes/ingress-stack/config-jackett:/config'
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${REVERSE_HOST}`)"
      - "traefik.http.routers.jackett.entrypoints=web-secure"
      - "traefik.http.routers.jackett.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse