version: '3.4'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - '../../volumes/firefly/upload:/var/www/html/storage/upload'
    env_file: .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`firefly.${REVERSE_HOST}`)"
      - "traefik.http.routers.firefly.entrypoints=web-secure"
      - "traefik.http.routers.firefly.tls=true"
      - "traefik.docker.network=reverse"
    networks:
      - reverse
      - internal
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 10s

  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ../../volumes/firefly/mysql:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 15s
      retries: 5
      start_period: 5s
      timeout: 10s

networks:
  reverse:
    external:
      name: reverse
  internal:
