version: '3.3'
services:
  huginn:
    volumes:
      - './mysql-data:/var/lib/mysql'
    image: huginn/huginn
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn.rule=Host(`huginn.${REVERSE_HOST}`)"
      - "traefik.http.routers.huginn.entrypoints=web-secure"
      - "traefik.http.routers.huginn.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse
          