version: '3.3'
services:
  huginn:
    image: huginn/huginn
    volumes:
      - '../../volumes/huginn/data:/var/lib/mysql'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn.rule=Host(`huginn.${REVERSE_HOST}`)"
      - "traefik.http.routers.huginn.entrypoints=web-secure"
      - "traefik.http.routers.huginn.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse
          