version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      
      ## Keep configs here.
      - /mnt/virt/gdrive/crypt/stash/stash/config:/root/.stash
      ## Point this at your collection.
      - /mnt/virt/gdrive/crypt/stash:/data
      - /mnt/virt/X:/data-x
      ## This is where your stash's metadata lives
      - /mnt/virt/gdrive/crypt/stash/stash/metadata:/metadata
      ## Any other cache content.
      - /mnt/virt/gdrive/crypt/stash/stash/cache:/cache
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/virt/gdrive/crypt/stash/stash/generated:/generated
      # Community Scrapers
      - /mnt/virt/gdrive/crypt/stash/stash/config/scrapers:/data/scrapers
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.stash.rule=Host(`stash.${REVERSE_HOST}`)"
      - "traefik.http.routers.stash.entrypoints=web-secure"
      - "traefik.http.routers.stash.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse
