version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'EST5EDT'
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
      - ./vpn/config:/vpn
    command: [-f, '']
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.soulseek.rule=Host(`soul.${REVERSE_HOST}`)"
      - "traefik.http.routers.soulseek.entrypoints=web-secure"
      - "traefik.http.routers.soulseek.tls=true"
      - "traefik.http.services.soulseek.loadbalancer.server.port=6080"
    networks: 
      - reverse

  soulseek:
    restart: unless-stopped
    depends_on:
      - vpn
    volumes:
        - './soulseek/appdata:/data/.SoulseekQt'
        - './soulseek/downloads:/data/Soulseek Downloads'
        - '/mnt/virt/Music:/Music'
        - './soulseek/logs:/data/Soulseek Chat Logs'
    environment:
        - pgid=1000
        - puid=1000
        - resize=scale
        - resolution=1280x720
    network_mode: "service:vpn"
    stdin_open: true
    tty: true
    image: realies/soulseek

networks:
  reverse:
    external:
      name: reverse
